name: Azure Governance Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: 27696e7f-98ff-45d4-85f6-3e7706b45e8a
          tenant-id: 3dd40eab-7747-46e7-9bae-600a1789287e
          subscription-id: 976b414b-46a7-4cd1-b4cf-349193150110

      - name: Test Azure Access
        run: az group list
